# Generated by Django 3.0.8 on 2020-07-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_feed_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date'),
        ),
    ]
