# Generated by Django 3.0.8 on 2020-07-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[(0, 'articles'), (1, 'Academics'), (2, 'Career'), (3, 'Science & Technology'), (4, 'Lifestyle')], default=0, max_length=30),
        ),
    ]
