# Generated by Django 3.0.8 on 2020-07-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('0', 'articles'), ('1', 'Academics'), ('2', 'Career'), ('3', 'Science & Technology'), ('4', 'Lifestyle')], default=0, max_length=30),
        ),
    ]
