# Generated by Django 3.0.8 on 2020-07-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200721_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image2',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Image 2'),
        ),
    ]
