# Generated by Django 3.0.8 on 2020-07-23 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_article_image2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
